$mainMod = SUPER
monitor = ,preferred,auto,1

general {
  gaps_in = 6
  gaps_out = 18
  border_size = 2
  col.active_border = rgba(8a2be2ff) rgba(00d2ffff) 45deg
  col.inactive_border = rgba(4b3869aa)
  layout = dwindle
  allow_tearing = false
}

decoration {
  rounding = 16
  active_opacity = 0.98
  inactive_opacity = 0.94
  fullscreen_opacity = 1.0
  shadow {
    enabled = true
    range = 28
    render_power = 3
    color = rgba(8a2be280)
  }
  blur {
    enabled = true
    size = 8
    passes = 3
    new_optimizations = true
    vibrancy = 0.12
  }
}

animations {
  enabled = true
  bezier = lunnaEase,0.16,1,0.3,1
  bezier = lunnaSmooth,0.22,1,0.36,1
  animation = windows,1,7,lunnaEase
  animation = windowsOut,1,6,lunnaSmooth,popin 80%
  animation = border,1,8,lunnaSmooth
  animation = fade,1,7,lunnaSmooth
  animation = workspaces,1,8,lunnaEase,slide
}

input {
  kb_layout = us
  follow_mouse = 1
  sensitivity = 0
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  vfr = true
}

bind = $mainMod, RETURN, exec, foot
bind = $mainMod, SPACE, exec, lunna-launcher
bind = $mainMod, Q, killactive
exec-once = systemctl --user start lunna-shell.service
